name: meals_app
description: Categories of different meals

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-Light.ttf
           weight : 200
         - asset: assets/fonts/Raleway-Regular.ttf
           weight : 400
         - asset: assets/fonts/Raleway-Medium.ttf
           weight : 500
         - asset: assets/fonts/Raleway-Bold.ttf
           weight : 700
         - asset: assets/fonts/Raleway-ExtraBold.ttf
           weight : 900
  assets:
       - assets/images/

